#include "codegen.h"

#include <cstdarg>
#include <cstdio>

namespace {

std::string Fmt(const char* f, ...) {
    char buf[512];
    va_list ap;
    va_start(ap, f);
    vsnprintf(buf, sizeof buf, f, ap);
    va_end(ap);
    return buf;
}

void AppendUtf8(std::string& o, uint32_t cp) {
    if (cp < 0x80) o += (char)cp;
    else if (cp < 0x800) { o += (char)(0xC0 | (cp >> 6)); o += (char)(0x80 | (cp & 0x3F)); }
    else {
        o += (char)(0xE0 | (cp >> 12));
        o += (char)(0x80 | ((cp >> 6) & 0x3F));
        o += (char)(0x80 | (cp & 0x3F));
    }
}

std::string CharLabel(uint32_t cp) {
    std::string s = Fmt("U+%04X '", (unsigned)cp);
    AppendUtf8(s, cp);
    return s + "'";
}

// Keeps free text from terminating the surrounding block comment.
std::string CommentSafe(std::string s) {
    for (size_t p; (p = s.find("*/")) != std::string::npos;) s.replace(p, 2, "* /");
    return s;
}

std::string Identifier(const std::wstring& stem) {
    std::string id;
    for (wchar_t c : stem) {
        if (c < 128 && iswalnum(c)) id += (char)towlower(c);
        else if (!id.empty() && id.back() != '_') id += '_';
    }
    while (!id.empty() && id.back() == '_') id.pop_back();
    if (id.empty()) id = "font";
    if (id[0] >= '0' && id[0] <= '9') id = "font_" + id;
    return id;
}

std::string Upper(std::string s) {
    for (char& c : s) if (c >= 'a' && c <= 'z') c = (char)(c - 32);
    return s;
}

bool IsMono(const RenderResult& r) { return r.mode == RenderMode::Mono1; }
int BytesPerRow(const RenderResult& r) { return IsMono(r) ? (r.cellW + 7) / 8 : r.cellW; }

void EmitRows(std::string& o, const RenderResult& r, const Glyph& g, const char* indent) {
    static const char ramp[] = " .:-=+*#%@";
    const int W = r.cellW;
    for (int y = 0; y < r.cellH; ++y) {
        const uint8_t* row = &g.px[(size_t)y * W];
        o += indent;
        if (IsMono(r)) {
            for (int b = 0; b < BytesPerRow(r); ++b) {
                unsigned byte = 0;
                for (int bit = 0; bit < 8; ++bit) {
                    int x = b * 8 + bit;
                    if (x < W && row[x] >= 128) byte |= 0x80u >> bit;
                }
                o += Fmt("0x%02X, ", byte);
            }
        } else {
            for (int x = 0; x < W; ++x) o += Fmt("0x%02X, ", row[x]);
        }
        o += "/* ";
        for (int x = 0; x < W; ++x)
            o += IsMono(r) ? (row[x] >= 128 ? '#' : '.') : ramp[row[x] * 9 / 255];
        o += " */\n";
    }
}

} // namespace

std::string ToUtf8(const std::wstring& w) {
    if (w.empty()) return {};
    int n = WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(), nullptr, 0, nullptr, nullptr);
    std::string s(n, '\0');
    WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(), s.data(), n, nullptr, nullptr);
    return s;
}

std::wstring FromUtf8(const std::string& s) {
    if (s.empty()) return {};
    int n = MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), nullptr, 0);
    std::wstring w(n, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), w.data(), n);
    return w;
}

std::string GenerateCFile(const RenderResult& r, const FontFile& font, const CharSet& cs) {
    const std::string name = Identifier(font.FileStem()) + Fmt("_%dx%d", r.cellW, r.cellH);
    const std::string NAME = Upper(name);
    const int bpr = BytesPerRow(r);
    const int bpc = bpr * r.cellH;
    const size_t count = r.glyphs.size();

    SYSTEMTIME st;
    GetLocalTime(&st);

    std::string o;
    o += "/*\n";
    o += " * Generated by Doppler's TTF to C\n";
    o += " *\n";
    o += " * Font file    : " + CommentSafe(ToUtf8(font.FileName())) + "\n";
    o += " * Font name    : " + CommentSafe(ToUtf8(font.DisplayName())) + "\n";
    o += Fmt(" * Generated    : %04d-%02d-%02d %02d:%02d:%02d\n",
             st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute, st.wSecond);
    o += Fmt(" * Char set     : %s, %u chars\n", cs.codeName, (unsigned)count);
    o += Fmt(" * Cell size    : %d x %d px (width x height)\n", r.cellW, r.cellH);
    o += Fmt(" * Font size    : %d px%s\n", r.fontPx, r.autoFit ? " (auto-fit to cell)" : "");
    o += Fmt(" * Baseline     : row %d from the top\n", r.baseline);
    if (IsMono(r)) {
        o += " * Pixel format : 1 bpp, rows top to bottom, MSB = leftmost pixel,\n";
        o += Fmt(" *                each row padded to %d byte(s), %d bytes per char\n", bpr, bpc);
    } else {
        o += " * Pixel format : 8 bpp grayscale (anti-aliased), rows top to bottom,\n";
        o += Fmt(" *                0x00 = background, 0xFF = full ink, %d bytes per char\n", bpc);
    }
    if (r.missing) {
        o += Fmt(" * Missing      : %d char(s) not in the font, replaced with spaces:\n *               ", r.missing);
        int col = 0;
        for (const Glyph& g : r.glyphs) {
            if (g.present) continue;
            if (col && col % 8 == 0) o += "\n *               ";
            o += Fmt(" U+%04X", (unsigned)g.cp);
            ++col;
        }
        o += "\n";
    }
    if (r.clipped)
        o += Fmt(" * Clipped      : %d char(s) did not fully fit the cell\n", r.clipped);
    o += " */\n\n";

    o += "#include <stdint.h>\n\n";
    const int pad = 8 + (int)NAME.size() + 16;   // "#define " + NAME + "_BYTES_PER_CHAR "
    auto def = [&](const char* suffix, int value) {
        std::string m = "#define " + NAME + "_" + suffix;
        if ((int)m.size() < pad) m.append(pad - m.size(), ' ');
        o += m + " " + std::to_string(value) + "\n";
    };
    def("WIDTH", r.cellW);
    def("HEIGHT", r.cellH);
    def("BPP", IsMono(r) ? 1 : 8);
    def("BYTES_PER_ROW", bpr);
    def("BYTES_PER_CHAR", bpc);
    def("CHAR_COUNT", (int)count);
    def("BASELINE", r.baseline);
    o += "\n";

    o += "static const uint8_t " + name + "[" + NAME + "_CHAR_COUNT][" + NAME + "_BYTES_PER_CHAR] = {\n";
    for (size_t i = 0; i < count; ++i) {
        const Glyph& g = r.glyphs[i];
        o += Fmt("    /* [%u] ", (unsigned)i) + CharLabel(g.cp) + (g.present ? "" : " - missing in font, replaced with space") + " */\n";
        o += "    {\n";
        EmitRows(o, r, g, "        ");
        o += "    },\n";
    }
    o += "};\n\n";

    o += "/* Returns the glyph index for a Unicode code point, or -1 if it is not included. */\n";
    o += "static inline int " + name + "_index(uint32_t cp)\n{\n";
    unsigned offset = 0;
    for (const CharRange& cr : cs.ranges) {
        if (cr.first == cr.last)
            o += Fmt("    if (cp == 0x%04Xu) return %u;\n", cr.first, offset);
        else
            o += Fmt("    if (cp >= 0x%04Xu && cp <= 0x%04Xu) return (int)(cp - 0x%04Xu) + %u;\n",
                     cr.first, cr.last, cr.first, offset);
        offset += cr.last - cr.first + 1;
    }
    o += "    return -1;\n}\n\n";

    o += "/* Returns the bitmap of a Unicode code point, or 0 if it is not included. */\n";
    o += "static inline const uint8_t *" + name + "_glyph(uint32_t cp)\n{\n";
    o += "    int i = " + name + "_index(cp);\n";
    o += "    return (i < 0) ? 0 : " + name + "[i];\n}\n";
    return o;
}

std::string GenerateGlyphSnippet(const RenderResult& r, size_t index) {
    if (index >= r.glyphs.size()) return {};
    const Glyph& g = r.glyphs[index];
    std::string o = Fmt("/* [%u] ", (unsigned)index) + CharLabel(g.cp);
    o += Fmt(" - %dx%d px, %d bpp, %d bytes%s */\n", r.cellW, r.cellH, IsMono(r) ? 1 : 8,
             BytesPerRow(r) * r.cellH, g.present ? "" : ", missing in font, replaced with space");
    o += "{\n";
    EmitRows(o, r, g, "    ");
    o += "},\n";
    return o;
}
